# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [96]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [97]:
# Import torch
import torch
print(torch.__version__)

# Create random tensor
r1 = torch.rand(size=(7,7))
r1

1.13.1+cu116


tensor([[0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204],
        [0.0731, 0.9699, 0.1078, 0.8829, 0.4132, 0.7572, 0.6948],
        [0.5209, 0.5932, 0.8797, 0.6286, 0.7653, 0.1132, 0.8559],
        [0.6721, 0.6267, 0.5691, 0.7437, 0.9592, 0.3887, 0.2214],
        [0.3742, 0.1953, 0.7405, 0.2529, 0.2332, 0.9314, 0.9575],
        [0.5575, 0.4134, 0.4355, 0.7369, 0.0331, 0.0914, 0.8994],
        [0.9936, 0.4703, 0.1049, 0.5137, 0.2674, 0.4990, 0.7447]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [98]:
# Create another random tensor
r2 = torch.rand(size=(1,7))
# Perform matrix multiplication 
r1 @ r2.transpose(1,0)

tensor([[1.6914],
        [1.7581],
        [2.0906],
        [1.8975],
        [1.7585],
        [1.7961],
        [1.8900]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [99]:
# Set manual seed
torch.manual_seed(0)
# Create two random tensors
r1 = torch.rand(7,7)
r2 = torch.rand(1,7)

# Matrix multiply tensors
mm1 = r1 @ r2.transpose(1,0) 

print(f'Using @ \n {mm1}')

mm2 = torch.mm(r1,r2.transpose(1,0)) 

print(f'Using torch.mm \n {mm2}')

Using @ 
 tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])
Using torch.mm 
 tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [100]:
# Set random seed on the GPU

torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [101]:
# Set random seed
torch.manual_seed(1234)
# Check for access to GPU
print(f" Is GPU Avaialable : {torch.cuda.is_available()}")

# Device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f" Device : {device} ")
# Create two random tensors on GPU
r1 = torch.rand(2,3).to(device)
r2 = torch.rand(2,3).to(device)
r1, r2

 Is GPU Avaialable : True
 Device : cuda 


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [102]:
# Perform matmul on tensor_A and tensor_B
mm3 = torch.matmul(r1,r2.transpose(1,0))
mm3, mm3.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [103]:
# Find max
print(f"The Maximum is : {mm3.max()}")
# Find min
print(f"The Minimum is : {mm3.min()}")

The Maximum is : 0.5617256760597229
The Minimum is : 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [104]:
row,col = mm3.shape

In [105]:
print(mm3.reshape(row*col))
# Find arg max
print(f"Index where max value occurs: {mm3.argmax()}")
# Find arg min
print(f"Index where min value occurs: {mm3.argmin()}")

tensor([0.3647, 0.4709, 0.5184, 0.5617], device='cuda:0')
Index where max value occurs: 3
Index where min value occurs: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [106]:
# Set seed
torch.manual_seed(7)

# Create random tensor
r = torch.rand(1,1,1,10)
print(" Random Tensor : ", r)
print('Shape of Random Tensor : ', r.shape)
print('\n\n')
# Remove single dimensions
r2 = r.squeeze()
# Print out tensors and their shapes
print(" Sequeezed Random Tensor : ", r2)
print('Shape of  Sequeezed Random Tensor : ', r2.shape)

 Random Tensor :  tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Shape of Random Tensor :  torch.Size([1, 1, 1, 10])



 Sequeezed Random Tensor :  tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Shape of  Sequeezed Random Tensor :  torch.Size([10])
